### ISSUE TITLE
Guide for newbies 2

### ISSUE THREAD

**Issue by Jozaca119988** [s3phir0th115/MMXLC1-Rom-Extractor#4]
So, I read read the issue that was closed before but I have the same question. Could you make a guide or something about how to do this for a total beginner? Because I have created a GitHub account so I can ask this question.

**Comment by s3phir0th115** [comment]
What sort of information would you be wanting in such a guide? I thought the readme was pretty clear but I understand if it needs additional information.

**Comment by Jozaca119988** [comment]
Well, I have no idea of how to run a python code.

**Comment by s3phir0th115** [comment]
If you don't already have it and need to get Python itself, and assuming you're on Windows, it's available here. I recommend the 64 bit installer: https://www.python.org/downloads/windows/

Python's official documentation covers running code pretty well. Also assuming you're on Windows: https://docs.python.org/3/faq/windows.html#how-do-i-run-a-python-program-under-windows

I don't consider explaining Python usage itself within the scope of the project though, so I'm going to close this out.
