### ISSUE TITLE
ROM injector

### ISSUE THREAD

**Issue by Jozaca119988** [s3phir0th115/MMXLC1-Rom-Extractor#5]
Hello, I don't know if I am bothering you. I am the same  guy who asked how to run the code. I have already run the code and It worked perfectly, thanks for the help. I don't know if this is the place for asking this type of questions or if there is a comment section, but do you know how can I inject a ROM back in the Steam Game?

**Comment by s3phir0th115** [comment]
Hi again,

You're welcome, glad it worked well.

The best place is probably contacting me on Reddit or email. These open issues against the general project.

I've injected a ROM back in before using a hex editor, though never made a tool to automate the task. You would get a desired ROM, sized to match the ROM you're replacing, and then you would overwrite the original ROM data in RCX1.exe using the offset the script shows. I never tested this exclusively beyond seeing Super Mario World boot and run.
