### ISSUE TITLE
Checksum doesn't match.

### ISSUE THREAD

**Issue by Leatherhide** [s3phir0th115/MMXLC1-Rom-Extractor#6]
Installed the game on 29-11-2023. Got error that the checksum doesn't match for the international version.
Edit: SteamDB confirmed the game was updated earlier in 2023.

**Comment by s3phir0th115** [comment]
Hello, thank you for the issue report, and my apologies for taking a while to look into it. I can confirm they updated it.

I've updated the script just now to fix this with the latest international release that I have. Please let me know if it works for you.

**Comment by RealRelativeEase** [comment]
#8 

The new SHA-512 for the Japanese version is `75785438024ca7bf4f819c7791060847dfc07ccb71ebb3d30661f985f67a829e915c735fbbf8da0d71fed8d0e46a90f68956b3de4797eabd142a88e81288dc81`.
