### ISSUE TITLE
New SHA-512 breaks extraction script

### ISSUE THREAD

**Issue by RealRelativeEase** [s3phir0th115/MMXLC1-Rom-Extractor#8]
I tried the script on the Japanese version of the collection, and it didn't work due to what I presume is a new SHA-512 hash value for the Japanese version of RXC1.exe due to updates. The new SHA-512 is: `75785438024ca7bf4f819c7791060847dfc07ccb71ebb3d30661f985f67a829e915c735fbbf8da0d71fed8d0e46a90f68956b3de4797eabd142a88e81288dc81`

 I was able to extract all six games successfully by editing the respective line manually before running the script.

**Comment by s3phir0th115** [comment]
Thanks for the updated checksum and for confirming it extracts fine without updating the offsets. I've updated the script and readme with the change.
